import 'package:neighsecure/models/dummy/entry_dummy_data.dart';
import 'package:neighsecure/models/dummy/user_dummy_data.dart';

import '../entities/permission.dart';
import 'home_dummy_data.dart';
import 'key_dummy_data.dart';

List<Permission> dummyPermissions = [
  Permission(
    id: '1',
    type: 'unica',
    startDate: DateTime.now(),
    endDate: DateTime.now().add(const Duration(days: 1)),
    startTime: DateTime.now(),
    endTime: DateTime.now().add(const Duration(hours: 1)),
    status: true,
    valid: true,
    key: dummyKeys[2],
    generationDate: DateTime.now(),
    days: 'Martes',
    entries: [dummyEntries[0]],
    invetedBy: 'Diego Campos',
    user: dummyUsers[8],
    home: dummyHomes[0],
  ),
  Permission(
    id: '2',
    type: 'unica',
    startDate: DateTime.now(),
    endDate: DateTime.now().add(const Duration(days: 2)),
    startTime: DateTime.now(),
    endTime: DateTime.now().add(const Duration(hours: 2)),
    status: false,
    valid: true,
    key: dummyKeys[1],
    generationDate: DateTime.now(),
    days: 'Lunes',
    entries: [dummyEntries[1]],
    invetedBy: 'Fernando Martinez',
    user: dummyUsers[7],
    home: dummyHomes[0],
  ),
  Permission(
    id: '3',
    type: 'unica',
    startDate: DateTime.now(),
    endDate: DateTime.now().add(const Duration(days: 2)),
    startTime: DateTime.now(),
    endTime: DateTime.now().add(const Duration(hours: 2)),
    status: true,
    valid: true,
    key: dummyKeys[1],
    generationDate: DateTime.now(),
    days: 'Lunes',
    entries: [dummyEntries[1]],
    invetedBy: 'Fernando Martinez',
    user: dummyUsers[7],
    home: dummyHomes[0],
  ),
  Permission(
    id: '4',
    type: 'multiple',
    startDate: DateTime.now(),
    endDate: DateTime.now().add(const Duration(days: 3)),
    startTime: DateTime.now(),
    endTime: DateTime.now().add(const Duration(hours: 3)),
    status: true,
    valid: false,
    key: dummyKeys[2],
    generationDate: DateTime.now(),
    days: 'Lunes, Martes, Miercoles, Jueves, Viernes, Sabado, Domingo',
    entries: [dummyEntries[1]],
    invetedBy: 'Pamela Martinez',
    user: dummyUsers[1],
    home: dummyHomes[0],
  ),
  Permission(
    id: '5',
    type: 'multiple',
    startDate: DateTime.now(),
    endDate: DateTime.now().add(const Duration(days: 3)),
    startTime: DateTime.now(),
    endTime: DateTime.now().add(const Duration(hours: 3)),
    status: true,
    valid: false,
    key: dummyKeys[0],
    generationDate: DateTime.now(),
    days: 'Lunes, Martes, Miercoles, Jueves, Viernes, Sabado, Domingo',
    entries: [dummyEntries[1]],
    invetedBy: 'David Martinez',
    user: dummyUsers[1],
    home: dummyHomes[0],
  ),
  Permission(
    id: '6',
    type: 'unica',
    startDate: DateTime.now(),
    endDate: DateTime.now().add(const Duration(days: 2)),
    startTime: DateTime.now(),
    endTime: DateTime.now().add(const Duration(hours: 2)),
    status: true,
    valid: true,
    key: dummyKeys[1],
    generationDate: DateTime.now(),
    days: 'Lunes',
    entries: [dummyEntries[1]],
    invetedBy: 'Fernando Martinez',
    user: dummyUsers[4],
    home: dummyHomes[0],
  ),
  Permission(
    id: '7',
    type: 'multiple',
    startDate: DateTime.now(),
    endDate: DateTime.now().add(const Duration(days: 3)),
    startTime: DateTime.now(),
    endTime: DateTime.now().add(const Duration(hours: 3)),
    status: true,
    valid: false,
    key: dummyKeys[2],
    generationDate: DateTime.now(),
    days: 'Lunes, Martes, Miercoles, Jueves, Viernes, Sabado, Domingo',
    entries: [dummyEntries[1]],
    invetedBy: 'Pamela Martinez',
    user: dummyUsers[4],
    home: dummyHomes[0],
  ),
];
